export type BlogTopic = "cataract" | "glaucoma" | "cornea" | "surgery" | "eye-health";

export interface BlogPostMeta {
  slug: string;
  title: string;
  url: string;
  coverImage: string;
  coverWidth: number;
  coverHeight: number;
  date: string;
  excerpt: string;
  readMinutes: number;
  topics: BlogTopic[];
}

// All 36 posts — 26 live (slugs/titles/URLs VERBATIM from the WordPress
// REST API; titles entity-decoded for display) + 10 hospital-authored docs
// from new_blog/ (titles/slugs/excerpts per doc front-matter, verbatim).
// coverImage = each post's own featured media, mirrored to
// public/images/blog-covers/ (26 JPG originals + 10 optimized WebP copies;
// PNG originals retained in new_blog/). date = WP publish date, or
// 2026-09-28/29/30 author dates for the 10 new posts. excerpt = source-text
// truncation (first sentence-ish, never rewritten). readMinutes = ceil from
// live word count, or doc READ TIME. topics = keyword-derived buckets (26)
// or doc CATEGORY mapping (10) for journal filtering (source taxonomy
// untouched).
export const blogPosts: BlogPostMeta[] = [
  {
    slug: "lasik-eye-surgery-types-cost-benefits-candidacy",
    title: "LASIK Eye Surgery Types, Cost, Benefits and Who Qualifies",
    url: "/blog/lasik-eye-surgery-types-cost-benefits-candidacy/",
    coverImage: "/images/blog-covers/lasik-eye-surgery-types-cost-benefits-candidacy.webp",
    coverWidth: 1280,
    coverHeight: 720,
    date: "2026-09-30",
    excerpt: "A plain guide to LASIK eye surgery in India, covering Femto-LASIK, Contoura, SMILE and PRK, indicative costs, recovery, and who makes a good candidate.",
    readMinutes: 16,
    topics: ["surgery"],
  },
  {
    slug: "diabetic-retinopathy-symptoms-screening-stages-treatment",
    title: "Diabetic Retinopathy: Symptoms, Screening, Stages & Treatment",
    url: "/blog/diabetic-retinopathy-symptoms-screening-stages-treatment/",
    coverImage: "/images/blog-covers/diabetic-retinopathy-symptoms-screening-stages-treatment.webp",
    coverWidth: 1280,
    coverHeight: 720,
    date: "2026-09-30",
    excerpt: "Diabetic retinopathy can develop without symptoms. Learn about its stages, screening, diabetic macular edema, treatment options and ways to protect vision.",
    readMinutes: 14,
    topics: ["eye-health"],
  },
  {
    slug: "eye-checkup-after-forty-tests-frequency-warning-signs",
    title: "Eye Check-Up After 40: Tests, Frequency & Warning Signs",
    url: "/blog/eye-checkup-after-forty-tests-frequency-warning-signs/",
    coverImage: "/images/blog-covers/eye-checkup-after-forty-tests-frequency-warning-signs.webp",
    coverWidth: 1280,
    coverHeight: 720,
    date: "2026-09-30",
    excerpt: "An eye check-up after 40 can pick up glaucoma, cataract and retinal changes before you notice them. Here's what the tests involve and how often you should go.",
    readMinutes: 16,
    topics: ["eye-health"],
  },
  {
    slug: "pterygium-causes-symptoms-stages-treatment-surgery",
    title: "Pterygium: Causes, Symptoms, Stages, Treatment & Surgery",
    url: "/blog/pterygium-causes-symptoms-stages-treatment-surgery/",
    coverImage: "/images/blog-covers/pterygium-causes-symptoms-stages-treatment-surgery.webp",
    coverWidth: 1280,
    coverHeight: 720,
    date: "2026-09-29",
    excerpt: "Pterygium is a non-cancerous growth on the white of the eye. Learn what causes it, how it is graded, when surgery helps, what recovery is like and how to prevent regrowth.",
    readMinutes: 15,
    topics: ["cornea", "surgery"],
  },
  {
    slug: "corneal-ulcer-keratitis-symptoms-treatment",
    title: "Corneal Ulcer & Keratitis: Symptoms & Treatment",
    url: "/blog/corneal-ulcer-keratitis-symptoms-treatment/",
    coverImage: "/images/blog-covers/corneal-ulcer-keratitis-symptoms-treatment.webp",
    coverWidth: 1280,
    coverHeight: 720,
    date: "2026-09-29",
    excerpt: "Corneal ulcers and keratitis can cause eye pain, redness and blurred vision. Learn the causes, symptoms, diagnosis, treatment and when urgent care is needed.",
    readMinutes: 15,
    topics: ["cornea"],
  },
  {
    slug: "cataract-surgery-guide",
    title: "Cataract Surgery: Symptoms, When Surgery Is Needed, Lens Options, Procedure & Recovery",
    url: "/blog/cataract-surgery-guide/",
    coverImage: "/images/mungale/specialty-cataract.jpg",
    coverWidth: 1600,
    coverHeight: 2000,
    date: "2026-09-28",
    excerpt: "A practical guide to cataract symptoms, when surgery is considered, cataract surgery steps, lens choices, recovery, risks and common patient questions.",
    readMinutes: 15,
    topics: ["cataract", "surgery"],
  },
  {
    slug: "corneal-transplant-surgery",
    title: "Corneal Transplant Surgery: When It Is Needed, Types, Recovery & Risks",
    url: "/blog/corneal-transplant-surgery/",
    coverImage: "/images/mungale/specialty-cornea.jpg",
    coverWidth: 1600,
    coverHeight: 2000,
    date: "2026-09-28",
    excerpt: "A corneal transplant is an operation in which damaged or diseased corneal tissue is replaced with healthy donor tissue. It may be considered when corneal disease cau…",
    readMinutes: 17,
    topics: ["cornea", "surgery"],
  },
  {
    slug: "dry-eye-disease-causes-symptoms-treatment",
    title: "Dry Eye Disease: Causes, Symptoms, Diagnosis & Treatment",
    url: "/blog/dry-eye-disease-causes-symptoms-treatment/",
    coverImage: "/images/mungale/blog-dry-eye-desktop.jpg",
    coverWidth: 1600,
    coverHeight: 900,
    date: "2026-09-28",
    excerpt: "Dry eye disease can cause burning, irritation and fluctuating vision. Learn about its causes, symptoms, diagnosis, treatment and long-term management.",
    readMinutes: 19,
    topics: ["cornea"],
  },
  {
    slug: "glaucoma-symptoms-causes-treatment",
    title: "Glaucoma: Symptoms, Causes, Eye Pressure Tests & Treatment",
    url: "/blog/glaucoma-symptoms-causes-treatment/",
    coverImage: "/images/mungale/specialty-glaucoma.jpg",
    coverWidth: 1600,
    coverHeight: 2000,
    date: "2026-09-28",
    excerpt: "Glaucoma often develops without warning signs. Learn its causes, symptoms, eye pressure tests, and treatment options from Mungale Eye Hospital, Vadodara.",
    readMinutes: 15,
    topics: ["glaucoma"],
  },
  {
    slug: "keratoconus-symptoms-causes-diagnosis-treatment",
    title: "Keratoconus: Symptoms, Causes, Diagnosis & Treatment",
    url: "/blog/keratoconus-symptoms-causes-diagnosis-treatment/",
    coverImage: "/images/blog-covers/keratoconus.webp",
    coverWidth: 1280,
    coverHeight: 720,
    date: "2026-09-28",
    excerpt: "Keratoconus causes the cornea to thin and bulge, blurring vision. Learn the symptoms, causes, diagnosis and treatment options, from cross-linking to lenses.",
    readMinutes: 14,
    topics: ["cornea", "surgery"],
  },
  {
    slug: "benchmarks-in-eye-care",
    title: "What Are Progression Measurement Benchmarks in Eye Care?",
    url: "/blog/benchmarks-in-eye-care/",
    coverImage: "/images/blog-covers/What-Are-Progression-Measurement-Benchmarks-in-Eye-Care.jpg",
    coverWidth: 800,
    coverHeight: 472,
    date: "2026-05-22",
    excerpt: "Progression measurement benchmarks in eye care are standardized metrics used to track the advancement of a chronic eye condition over time.",
    readMinutes: 6,
    topics: ["eye-health"],
  },
  {
    slug: "routine-eye-examination",
    title: "What Is Involved in a Routine Eye Examination?",
    url: "/blog/routine-eye-examination/",
    coverImage: "/images/blog-covers/What-Is-Involved-in-a-Routine-Eye-Examination.jpg",
    coverWidth: 800,
    coverHeight: 472,
    date: "2026-05-14",
    excerpt: "The best routine eye examination is a comprehensive evaluation because it tests both visual acuity and physical eye structures to detect underlying conditions early .",
    readMinutes: 6,
    topics: ["eye-health"],
  },
  {
    slug: "disease-progression-velocity-in-eye-care",
    title: "How to Calculate Disease Progression Velocity in Eye Care",
    url: "/blog/disease-progression-velocity-in-eye-care/",
    coverImage: "/images/blog-covers/Untitled-1-7.jpg",
    coverWidth: 800,
    coverHeight: 472,
    date: "2026-05-13",
    excerpt: "Disease progression velocity in eye care calculates the rate of structural and functional deterioration over time by applying linear regression to visual field data…",
    readMinutes: 6,
    topics: ["eye-health"],
  },
  {
    slug: "corneal-treatment-recovery-process",
    title: "What is the recovery process like after corneal treatment?",
    url: "/blog/corneal-treatment-recovery-process/",
    coverImage: "/images/blog-covers/What-is-the-recovery-process-like-after-corneal-treatment.jpg",
    coverWidth: 800,
    coverHeight: 472,
    date: "2026-05-11",
    excerpt: "The best approach to corneal treatment recovery is strict adherence to clinical aftercare protocols because it minimizes the risk of graft rejection and accelerates…",
    readMinutes: 6,
    topics: ["cornea"],
  },
  {
    slug: "how-is-glaucoma-diagnosed-evaluated",
    title: "How is Glaucoma Typically Diagnosed and Evaluated?",
    url: "/blog/how-is-glaucoma-diagnosed-evaluated/",
    coverImage: "/images/blog-covers/How-is-glaucoma-typically-diagnosed-and-evaluated.jpg",
    coverWidth: 800,
    coverHeight: 472,
    date: "2026-05-08",
    excerpt: "Glaucoma diagnosed through a comprehensive eye examination that measures intraocular pressure, evaluates the optic nerve for damage, and assesses peripheral vision loss.",
    readMinutes: 6,
    topics: ["glaucoma"],
  },
  {
    slug: "risks-benefits-of-cataract-surgery",
    title: "What are the risks and benefits of cataract surgery?",
    url: "/blog/risks-benefits-of-cataract-surgery/",
    coverImage: "/images/blog-covers/Benefits-of-Cataract-Surgery-for-Better-Vision-in-Daily-Life.jpg",
    coverWidth: 800,
    coverHeight: 427,
    date: "2026-04-24",
    excerpt: "Cataract Surgery: Navigating the Risks and Embracing the Benefits A cataract is a clouding of the eye’s natural lens, which can significantly impair vision and…",
    readMinutes: 6,
    topics: ["cataract", "surgery"],
  },
  {
    slug: "the-benefits-of-regular-eye-check-ups",
    title: "What are the benefits of regular eye check-ups?",
    url: "/blog/the-benefits-of-regular-eye-check-ups/",
    coverImage: "/images/blog-covers/What-are-the-benefits-of-regular-eye-check-ups.jpg",
    coverWidth: 800,
    coverHeight: 427,
    date: "2026-04-23",
    excerpt: "The Crucial Importance of Regular Eye Check-ups for Your Vision and Health Our vision is one of our most precious senses, allowing us to experience the world in…",
    readMinutes: 4,
    topics: ["eye-health"],
  },
  {
    slug: "glaucoma-treatment-options",
    title: "What are the different treatment options for glaucoma?",
    url: "/blog/glaucoma-treatment-options/",
    coverImage: "/images/blog-covers/mungale-eye-blog-copy.jpg",
    coverWidth: 800,
    coverHeight: 427,
    date: "2026-03-30",
    excerpt: "Glaucoma Treatment Options: A Comprehensive Guide Glaucoma is a group of eye conditions that damage the optic nerve, which is vital for good vision.",
    readMinutes: 7,
    topics: ["glaucoma"],
  },
  {
    slug: "benefits-of-cataract-surgery",
    title: "Benefits of Cataract Surgery for Better Vision in Daily Life",
    url: "/blog/benefits-of-cataract-surgery/",
    coverImage: "/images/blog-covers/mungale-eye-blog.jpg",
    coverWidth: 800,
    coverHeight: 427,
    date: "2026-03-23",
    excerpt: "Benefits of Cataract Surgery for Better Vision in Daily Life Cataracts rarely announce themselves. They creep in quietly.",
    readMinutes: 6,
    topics: ["cataract", "surgery"],
  },
  {
    slug: "best-foods-for-eye-health",
    title: "Best Foods for Eye Health: 15 Superfoods to Improve Your Vision Naturally",
    url: "/blog/best-foods-for-eye-health/",
    coverImage: "/images/blog-covers/blog-copy-2.jpg",
    coverWidth: 800,
    coverHeight: 427,
    date: "2026-02-26",
    excerpt: "Your eyes need food just as much as your body does. And what you eat every single day—at breakfast, lunch, and dinner—is either protecting your vision or slowly…",
    readMinutes: 15,
    topics: ["eye-health"],
  },
  {
    slug: "ai-in-eye-care-in-2026",
    title: "AI in Eye Care: How Artificial Intelligence is Revolutionising Eye Disease Detection in 2026",
    url: "/blog/ai-in-eye-care-in-2026/",
    coverImage: "/images/blog-covers/blog-3.jpg",
    coverWidth: 800,
    coverHeight: 427,
    date: "2026-02-25",
    excerpt: "Imagine a machine scanning your retina in seconds and detecting a disease your doctor hasn’t noticed yet. This isn’t science fiction – it’s happening right now in…",
    readMinutes: 11,
    topics: ["eye-health"],
  },
  {
    slug: "new-year-eye-health-resolutions-2026",
    title: "7 Habit for New Year Eye Health Resolutions 2026",
    url: "/blog/new-year-eye-health-resolutions-2026/",
    coverImage: "/images/blog-covers/New-Year-resulation-2026.jpg",
    coverWidth: 800,
    coverHeight: 427,
    date: "2026-01-13",
    excerpt: "As we welcome 2026, many of us are setting resolutions for better health. But here’s a question: when was the last time you thought about your eye health ?",
    readMinutes: 11,
    topics: ["eye-health"],
  },
  {
    slug: "glaucoma-awareness-month-2026",
    title: "Glaucoma Awareness Month 2026: Early Detection Is Key to Stopping the Silent Thief of Sight",
    url: "/blog/glaucoma-awareness-month-2026/",
    coverImage: "/images/blog-covers/Glaucoma-Awareness-Month-2026.jpg",
    coverWidth: 1080,
    coverHeight: 576,
    date: "2026-01-08",
    excerpt: "January is Glaucoma Awareness Month 2026 , a critical time to spotlight one of India’s most devastating yet preventable causes of blindness.",
    readMinutes: 3,
    topics: ["glaucoma"],
  },
  {
    slug: "corneal-ulcer-treatment",
    title: "Corneal Ulcer Treatment: Causes, Early Warning Signs, and the Importance of Timely Cornea Evaluation at Mungale Eye Hospital",
    url: "/blog/corneal-ulcer-treatment/",
    coverImage: "/images/blog-covers/blog-2.jpg",
    coverWidth: 1080,
    coverHeight: 576,
    date: "2025-12-16",
    excerpt: "Corneal Ulcer Treatment Starts With Early Awareness A corneal ulcer is an open wound on the cornea, the clear front layer of the eye that is essential for sharp vision.",
    readMinutes: 4,
    topics: ["cornea"],
  },
  {
    slug: "thinking-of-lasik-surgery",
    title: "Thinking of LASIK Read This Before You Book Your Surgery",
    url: "/blog/thinking-of-lasik-surgery/",
    coverImage: "/images/blog-covers/mungale.jpg",
    coverWidth: 800,
    coverHeight: 450,
    date: "2025-11-25",
    excerpt: "If you live in Vadodara you probably know at least one friend or colleague who has gone for LASIK eye surgery. People from Ahmedabad and other parts of Gujarat also…",
    readMinutes: 6,
    topics: ["surgery"],
  },
  {
    slug: "when-should-you-see-an-eye-doctor",
    title: "When Should You See an Eye Doctor? Let’s Talk About It Honestly",
    url: "/blog/when-should-you-see-an-eye-doctor/",
    coverImage: "/images/blog-covers/mungale-blog-image-1.jpg",
    coverWidth: 1920,
    coverHeight: 1080,
    date: "2025-11-12",
    excerpt: "We all do it. Ignore small eye problems. Rub them. Splash water. Move on. When Should You See an Eye Doctor? Then one fine day, the board at school looks hazy, or…",
    readMinutes: 4,
    topics: ["eye-health"],
  },
  {
    slug: "best-eye-hospital-near-me",
    title: "Where to Find the Right Eye Hospital Near Me in Vadodara: A Local’s Complete Guide to Healthy Vision",
    url: "/blog/best-eye-hospital-near-me/",
    coverImage: "/images/blog-covers/2241257-e1726640314227.jpg",
    coverWidth: 1000,
    coverHeight: 443,
    date: "2025-10-28",
    excerpt: "Whether you live in Akota, Alkapuri, Manjalpur, or the old city areas of Vadodara, your eyes deserve regular care -just like your heart or teeth.",
    readMinutes: 10,
    topics: ["eye-health"],
  },
  {
    slug: "best-eye-hospital-for-corneal-transplant",
    title: "Best Eye Hospital for Corneal Transplant – Munagle Eye Hospital",
    url: "/blog/best-eye-hospital-for-corneal-transplant/",
    coverImage: "/images/blog-covers/Corneal-Health-Demystified.jpg",
    coverWidth: 1920,
    coverHeight: 1080,
    date: "2025-09-24",
    excerpt: "Imagine trying to look through a window that has slowly fogged up over time. You can still make out shapes, but the details are gone.",
    readMinutes: 4,
    topics: ["cornea", "surgery"],
  },
  {
    slug: "cataract-surgery-vadodara-gujarat",
    title: "Cataract Surgery Vadodara Gujarat: From Subtle Symptoms to Clear Vision",
    url: "/blog/cataract-surgery-vadodara-gujarat/",
    coverImage: "/images/blog-covers/Cataract-Surgery.jpg",
    coverWidth: 1920,
    coverHeight: 1080,
    date: "2025-09-22",
    excerpt: "Introduction Cataract Surgery Vadodara Gujarat : You don’t wake up one morning and suddenly “have” cataracts. They creep in.",
    readMinutes: 4,
    topics: ["cataract", "surgery"],
  },
  {
    slug: "advanced-eye-care-treatment",
    title: "Advanced Eye Care Treatment in Raopura Vadodara",
    url: "/blog/advanced-eye-care-treatment/",
    coverImage: "/images/blog-covers/blog-copy3.jpg",
    coverWidth: 1080,
    coverHeight: 576,
    date: "2025-09-19",
    excerpt: "Advanced Eye Care Treatment in Raopura Vadodara Access to timely and accurate eye care plays a crucial role in preserving vision and preventing long-term complications.",
    readMinutes: 4,
    topics: ["eye-health"],
  },
  {
    slug: "ahmed-glaucoma-valve-surgery",
    title: "Ahmed Glaucoma Valve Surgery: How This Drainage Device Can Save Your Vision",
    url: "/blog/ahmed-glaucoma-valve-surgery/",
    coverImage: "/images/blog-covers/Ahmed-Glaucoma-Valve-Surgery-How-This-Drainage-Device-Can-Save-Your-Vision.jpg",
    coverWidth: 1024,
    coverHeight: 494,
    date: "2025-08-07",
    excerpt: "Introduction In Vadodara and across Gujarat, glaucoma is an increasingly common concern, especially among adults over 40 and diabetic patients.",
    readMinutes: 4,
    topics: ["glaucoma", "surgery"],
  },
  {
    slug: "best-eye-hospital-in-vadodara",
    title: "Best Eye Hospital in Vadodara – A Complete Guide to Choosing the Right Eye Care Provider",
    url: "/blog/best-eye-hospital-in-vadodara/",
    coverImage: "/images/blog-covers/How-to-Choose-the-Right-Eye-Hospital-A-Complete-Guide-for-Vadodara-Residents.jpg",
    coverWidth: 1024,
    coverHeight: 494,
    date: "2025-07-30",
    excerpt: "Best eye hospital in Vadodara – What issues may come to your mind when you search for an “Eye Hospital near Me?” Blurry vision?",
    readMinutes: 5,
    topics: ["eye-health"],
  },
  {
    slug: "advanced-eye-care-in-vadodara",
    title: "Breakthrough Treatments: How Specialists Are Advancing Eye Care in Vadodara, Gujarat",
    url: "/blog/advanced-eye-care-in-vadodara/",
    coverImage: "/images/blog-covers/Breakthrough-Treatments-How-Specialists-Are-Advancing-Eye-Care-in-Vadodara-Gujarat.jpg",
    coverWidth: 1024,
    coverHeight: 494,
    date: "2025-07-30",
    excerpt: "Eye Care in Vadodara, the centre of Gujarat, something is unfolding. Eye care is no longer restricted to old-fashioned surgeries or tedious waiting lists for donor…",
    readMinutes: 4,
    topics: ["eye-health"],
  },
  {
    slug: "5-easy-eye-care-tips-for-computer-geeks",
    title: "5 Easy Eye Care Tips For Computer Geeks",
    url: "/blog/5-easy-eye-care-tips-for-computer-geeks/",
    coverImage: "/images/blog-covers/232.jpg",
    coverWidth: 1480,
    coverHeight: 727,
    date: "2025-05-15",
    excerpt: "5 Easy Eye Care Tips- Spending long hours in front of computers, laptops, or televisions has become a part of modern man’s life today.",
    readMinutes: 2,
    topics: ["eye-health"],
  },
  {
    slug: "7-eye-care-tips-never-ignore",
    title: "7 Eye Care Helpful tips That You Need to Never Sacrifice On",
    url: "/blog/7-eye-care-tips-never-ignore/",
    coverImage: "/images/blog-covers/2-scaled-1.jpg",
    coverWidth: 2560,
    coverHeight: 1247,
    date: "2024-09-13",
    excerpt: "7 Eye Care tips-We are spending money for unnecessary things such as unnecessary shopping, having fast foods, movie and other needless things.",
    readMinutes: 3,
    topics: ["eye-health"],
  },
  {
    slug: "tips-for-choosing-an-eye-care-doctor",
    title: "Tips For Choosing an Eye Care Doctor",
    url: "/blog/tips-for-choosing-an-eye-care-doctor/",
    coverImage: "/images/blog-covers/Varun-Eye-Care-Slider-img.jpg",
    coverWidth: 1024,
    coverHeight: 494,
    date: "2024-09-13",
    excerpt: "Taking care of your eyes is good as giving importance to your overall health. Here are tips for choosing an eye care doctor is considered as an important health care…",
    readMinutes: 3,
    topics: ["eye-health"],
  },
];

export function getPostBySlug(slug: string): BlogPostMeta | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export function getPostSlugs(): string[] {
  return blogPosts.map((p) => p.slug);
}
